module LibRNP
  PGP_KEY_ID_SIZE = 8
  PGP_FINGERPRINT_SIZE = 20
  PGP_MAX_KEY_SIZE = 32
  PGP_SALT_SIZE = 8
  PGP_MAX_BLOCK_SIZE = 16
  SHA_DIGEST_LENGTH = 20
  PGP_SHA1_HASH_SIZE = SHA_DIGEST_LENGTH
  PGP_CHECKHASH_SIZE = PGP_SHA1_HASH_SIZE
end

